export const language = {
  "es": {
    inicioNav: "Inicio",
    skillsNav: "Habilidades",
    skillSoftNav: "Hab. Blandas",
    projectsNav: "Proyectos",
    contactoNav: "Contacto",
    subTitleGral: "Desarrollador Full Stack",
    descripcionGral: "Creo experiencias digitales excepcionales y accesibles para la web. Me apasiona crear aplicaciones intuitivas y responsivas que resuelvan problemas del mundo real.",
    cvDownload: "Mi CV",
    tecHabTitle: "Habilidades Técnicas",
    tecHabSubtitle: "Estas son algunas de las tecnologías con las que trabajo a diario.",
    softSkillTitleGral: "Habilidades Blandas",
    softSkillSubTitleGral: "Más allá de la experiencia técnica, estas habilidades interpersonales me ayudan a colaborar de manera efectiva y a lograr resultados excepcionales.",
    softSkillTitle: [
      "Trabajo en Equipo",
      "Resolución de Problemas",
      "Aprendizaje Rápido",
      "Manejo de Conflictos",
      "Comunicación",
      "Gestión del Tiempo"
    ],
    softSkillDescription: [
      "Colaborar de manera efectiva con equipos multidisciplinarios para alcanzar objetivos comunes.",
      "Analizar problemas complejos y desarrollar soluciones innovadoras a desafíos técnicos.",
      "Adaptarse rápidamente a nuevas tecnologías, frameworks y entornos de desarrollo.",
      "Navegar desacuerdos de forma constructiva para mantener la armonía y productividad del equipo.",
      "Articular conceptos técnicos claramente tanto para audiencias técnicas como no técnicas.",
      "Priorizar tareas eficientemente y cumplir con los plazos en entornos de desarrollo dinámicos.",
    ],
    projectsTitleGral: "Mis Proyectos",
    projectSubTitleGral: "Aquí están algunos de los proyectos en los que he trabajado. Cada uno representa un desafío único y una oportunidad de aprendizaje.",
    contactTitle: "Ponte en Contacto",
    contactSubTitle: "¿Tienes alguna pregunta o te gustaría trabajar juntos? ¡No dudes en contactarme!",
    name: "Nombre",
    namePHolder: "Tu Nombre",
    email: "Email",
    emailPHolder: "Tu Email",
    subject: "Asunto",
    message: "Mensaje",
    messagepHolder: "Tu Mensaje",
    contactSendMsg: "Enviar Mensaje",
    contactSending: "Enviando...",
    contactMsgSubmitAccert: "¡Tu mensaje ha sido enviado con éxito! Me pondré en contacto contigo pronto.",
    contactMsgSubmitError: "Hubo un error al enviar tu mensaje. Por favor, intenta nuevamente más tarde.",
    copy: "Todos los derechos reservados.",
    footerMsg: "Diseñado y construido con",
    projectsTitles: ["Fixture Creator", "Ecommerce Nuts", "Pokecrisdle", "Movistar gestor de ventas" , "Piedra Papel y Tijera", "Clon de Netflix"],
    projectDescription: [
      "Una app creada para crear fixtures de partidos de competición.",
      "Una página web dedicada al comercio de productos de frutos secos.",
      "Una página dedicada al conocimiento de pokemon, tienes que intentar adivinar un pokemon random.",
      "Una app mobile de movistar para gestionar las ventas del equipo, con gestion de usuarios y administrador",
      "Una app mobile con el clasico juego de piedra papel y tijera.",
      "Una página clonando la pagina de netflix",
    ]
  },
  "en": {
    inicioNav: "Home",
    skillsNav: "Skills",
    skillSoftNav: "Soft Skills",
    projectsNav: "Projects",
    contactoNav: "Contact Me",
    subTitleGral: "Full Stack Developer",
    descripcionGral: "I create exceptional and accessible digital experiences for the web. I am passionate about building intuitive and responsive applications that solve real-world problems.",
    cvDownload: "My Resume",
    tecHabTitle: "Technical Skills",
    tecHabSubtitle: "Here are some of the technologies I work with on a daily basis.",
    softSkillTitleGral: "Soft Skills",
    softSkillSubTitleGral: "Beyond technical expertise, these interpersonal skills help me collaborate effectively and deliver exceptional results.",
    softSkillTitle: [
      "Teamwork",
      "Problem Solving",
      "Quick Learning",
      "Conflict Management",
      "Communication",
      "Time Management"
    ],
    softSkillDescription: [
      "Collaborate effectively with cross-functional teams to achieve common goals.",
      "Analyze complex issues and develop innovative solutions to technical challenges.",
      "Rapidly adapt to new technologies, frameworks, and development environments.",
      "Navigate disagreements constructively to maintain team harmony and productivity.",
      "Clearly articulate technical concepts to both technical and non-technical stakeholders.",
      "Efficiently prioritize tasks and meet deadlines in fast-paced development environments.",
    ],
    projectsTitleGral: "My Projects",
    projectSubTitleGral: "Here are some of the projects I've worked on. Each one represents a unique challenge and learning opportunity.",
    contactTitle: "Get In Touch",
    contactSubTitle: "Have a question or want to work together? Feel free to reach out!",
    name: "Name",
    namePHolder: "Your Name",
    email: "Email",
    emailPHolder: "Your Email",
    subject: "Subject",
    message: "Message",
    messagepHolder: "Your Message",
    contactSendMsg: "Enviar Mensaje",
    contactSending: "Sending...",
    contactMsgSubmitAccert: "Your message has been sent successfully! I will get back to you soon.",
    contactMsgSubmitError: "There was an error sending your message. Please try again later.",
    copy: "All rights reserved.",
    footerMsg: "Designed and built with",
    projectsTitles: ["Fixture Creator", "Ecommerce Nuts", "Pokecrisdle", "Movistar Sales Manager" , "Rock Paper Scissors", "Clone Netflix"],
    projectDescription: [
      "An app created to create competitive match fixtures.",
      "A website dedicated to the trade of dried fruit products.",
      "A page dedicated to Pokémon knowledge, you have to try to guess a random Pokémon..",
      "A Movistar mobile app for managing team sales, with user and administrator management.",
      "A mobile app with the classic game of rock, paper, scissors.",
      "A page cloning the Netflix page",
    ]
  }
}